site_name: image-dataset-converter examples
site_url: https://www.data-mining.co.nz/image-dataset-converter-examples/
repo_url: https://github.com/waikato-datamining/image-dataset-converter-examples
edit_uri: edit/master/docs/
site_description: Examples for using the image-dataset-converter libraries
theme:
    name: material
markdown_extensions:
    - toc:
          baselevel: 2
          permalink: "#"
    - attr_list
plugins:
    - search
nav:
    - Home: index.md
    - Core library:
        - Image classification: image_classification.md
        - Object detection: object_detection.md
        - Image segmentation: image_segmentation.md
        - Filter usage: filters.md
        - Placeholders: placeholders.md
        - Docker usage: docker.md
        - External functions: pyfunc.md
        - Multiple I/O: multi.md
    - Additional libraries:
        - Image augmentation: imgaug.md
        - Image statistics: imgstats.md
        - Image visualizations: imgvis.md
        - labelme: labelme.md
        - Paddle: paddle.md
        - PDF: pdf.md
        - PlantCV: plantcv.md
        - Redis: redis.md
        - Video: video.md
    - Practical examples:
        - Depth estimation in videos: depth_estimation_in_videos.md
        - Objeft detection in videos: object_detection_in_videos.md
        - SpeciesNet: speciesnet.md
